name: build-deploy-app

on:
  workflow_dispatch:
    branches:
      - master
  push:
    paths:
      - 'src/**'
    branches:
      - master

env:
  S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_API_URL: ${{ vars.API_DOMAIN }}
          envkey_REACT_APP_GOOGLE_OAUTH_LOGIN_URL: ${{ vars.GOOGLE_OAUTH_LOGIN_URL }}
          envkey_REACT_APP_GOOGLE_OAUTH_SIGNIN_URL: ${{ vars.GOOGLE_OAUTH_SIGNIN_URL }}
          directory: ./
          file_name: .env
          fail_on_empty: true

      - name: Build
        working-directory: ./
        run: |
          yarn
          yarn build
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload to S3
        working-directory: ./build
        run: |
          aws s3 sync . s3://$S3_BUCKET_NAME
